# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33e49369abba3b43dd67c813c13f0b62cc5278eb7bbba1edfb416dd4120887454eb7a720c20b5a60cf39de89cdd3e98b753113248ea9da40bbf352b371952821

test:
  secret_key_base: 68f5e69bd6e3e59d25ab314dbe65904232023b6795d1a62238538e448c2b2796dae27b431ea9bebd0d7e818b6252a5123eebd531829b31ef0260fd9d65766a5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
